config/routes.rb
Rails.application.routes.draw do

  resources :needs do
    resources :pictures
  end

  resources :helpers do
    resources :schedules
  end

  resources :categories do
    resources :helpers
    resources :needs
  end

  get "/view_picture/:id" => "pictures#view_picture", :as => :view_picture

end

app/models/need.rb
class Need < ActiveRecord::Base
  belongs_to :category
  has_many :pictures
end

app/controllers/needs_controller.rb
class NeedsController < ApplicationController
  before_action :set_need, only: [:show, :edit, :update, :destroy]

  # GET /needs
  # GET /needs.json
  def index
    @needs = Need.all
  end

  # GET /needs/1
  # GET /needs/1.json
  def show
  end

  # GET /needs/new
  def new
    @need = Need.new
  end

  # GET /needs/1/edit
  def edit
  end

  # POST /needs
  # POST /needs.json
  def create
    @need = Need.new(need_params)

    respond_to do |format|
      if @need.save
        format.html { redirect_to @need, notice: 'Need was successfully created.' }
        format.json { render :show, status: :created, location: @need }
      else
        format.html { render :new }
        format.json { render json: @need.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /needs/1
  # PATCH/PUT /needs/1.json
  def update
    respond_to do |format|
      if @need.update(need_params)
        format.html { redirect_to @need, notice: 'Need was successfully updated.' }
        format.json { render :show, status: :ok, location: @need }
      else
        format.html { render :edit }
        format.json { render json: @need.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /needs/1
  # DELETE /needs/1.json
  def destroy
    @need.destroy
    respond_to do |format|
      format.html { redirect_to needs_url, notice: 'Need was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_need
      @need = Need.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def need_params
      params.require(:need).permit(:category_id, :title, :description, :tel, :facebook, :email, :comment)
    end
end

app/helpers/needs_helper.rb
module NeedsHelper
end

app/views/needs/_form.html.erb
<%= form_for(@need) do |f| %>
  <% if @need.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@need.errors.count, "error") %> prohibited this need from being saved:</h2>

      <ul>
      <% @need.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
    <%= link_to 'ジャンル追加', new_category_path %>

  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :facebook %><br>
    <%= f.text_field :facebook %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/needs/edit.html.erb
<h1>Editing need</h1>

<%= render 'form' %>

<%= link_to 'Show', @need %> |
<%= link_to 'Back', needs_path %>

app/views/needs/index.html.erb
<h1>お願い一覧</h1>

<table>
  <thead>
    <tr>
      <th>ジャンル</th>
      <th>件名</th>
      <th>詳細</th>
      <th>電話番号</th>
      <th>Facebookアカウント（あれば）</th>
      <th>メールアドレス</th>
      <th>備考</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @needs.each do |need| %>
      <tr>
        <td><%= need.category.name %></td>
        <td><%= need.title %></td>
        <td><%= need.description %></td>
        <td><%= need.tel %></td>
        <td><%= need.facebook %></td>
        <td><%= need.email %></td>
        <td><%= need.comment %></td>
        <td><%= link_to '詳細（写真付き）', need %></td>
        <td><%= link_to '編集', edit_need_path(need) %></td>
        <td><%= link_to '削除', need, method: :delete, data: { confirm: '削除して良いですか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'お願い追加', new_need_path %>

app/views/needs/new.html.erb
<h1>新しいお願い追加</h1>

<%= render 'form' %>

<%= link_to 'お願い一覧に戻る', needs_path %>

app/views/needs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @need.category.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @need.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @need.description %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @need.tel %>
</p>

<p>
  <strong>Facebook:</strong>
  <%= @need.facebook %>
</p>

<p>
  <strong>Email:</strong>
  <%= @need.email %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @need.comment %>
</p>

<% @need.pictures.each do |picture| %>
    <table>
      <tr>
        <td><%= image_tag view_picture_path(picture)%></td>
        <td><%= link_to '削除', need_picture_path(@need, picture), method: :delete, data: { confirm: '写真を削除して良いですか？' } %></td>
      </tr>
    </table>
<% end %>

<%= link_to '写真追加', new_need_picture_path(@need) %>
<br>
<%= link_to 'ニーズ一覧に戻る', needs_path %>