config/routes.rb
Rails.application.routes.draw do

  resources :needs do
    resources :pictures
  end

  resources :helpers do
    resources :schedules
  end

  resources :categories do
    resources :helpers
    resources :needs
  end

  get "/view_picture/:id" => "pictures#view_picture", :as => :view_picture

end

app/controllers/helpers_controller.rb
class HelpersController < ApplicationController
  before_action :set_helper, only: [:show, :edit, :update, :destroy]

  # GET /helpers
  # GET /helpers.json
  def index
    @helpers = Helper.all
  end

  # GET /helpers/1
  # GET /helpers/1.json
  def show
  end

  # GET /helpers/new
  def new
    @helper = Helper.new
  end

  # GET /helpers/1/edit
  def edit
  end

  # POST /helpers
  # POST /helpers.json
  def create
    @helper = Helper.new(helper_params)

    respond_to do |format|
      if @helper.save
        format.html { redirect_to @helper, notice: 'Helper was successfully created.' }
        format.json { render :show, status: :created, location: @helper }
      else
        format.html { render :new }
        format.json { render json: @helper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /helpers/1
  # PATCH/PUT /helpers/1.json
  def update
    respond_to do |format|
      if @helper.update(helper_params)
        format.html { redirect_to @helper, notice: 'Helper was successfully updated.' }
        format.json { render :show, status: :ok, location: @helper }
      else
        format.html { render :edit }
        format.json { render json: @helper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /helpers/1
  # DELETE /helpers/1.json
  def destroy
    @helper.destroy
    respond_to do |format|
      format.html { redirect_to helpers_url, notice: 'Helper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_helper
      @helper = Helper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def helper_params
      params.require(:helper).permit(:category_id, :skill, :tel, :email, :facebook, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/helpers_helper.rb
module HelpersHelper
end

app/helpers/needs_helper.rb
module NeedsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/helpers/_form.html.erb
<%= form_for(@helper) do |f| %>
  <% if @helper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@helper.errors.count, "error") %> prohibited this helper from being saved:</h2>

      <ul>
      <% @helper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
    <%= link_to 'ジャンル追加', new_category_path %>


  </div>
  <div class="field">
    <%= f.label :skill %><br>
    <%= f.text_field :skill %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :facebook %><br>
    <%= f.text_field :facebook %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/helpers/edit.html.erb
<h1>Editing helper</h1>

<%= render 'form' %>

<%= link_to '詳細', @helper %> |
<%= link_to '一覧に戻る', helpers_path %>

app/views/helpers/index.html.erb
<h1>お手伝いさん一覧</h1>

<table>
  <thead>
    <tr>
      <th>ジャンル</th>
      <th>スキル、特技</th>
      <th>電話番号</th>
      <th>メールアドレス</th>
      <th>Facebookアカウント</th>
      <th>備考</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @helpers.each do |helper| %>
      <tr>
        <td><%= helper.category.name %></td>
        <td><%= helper.skill %></td>
        <td><%= helper.tel %></td>
        <td><%= helper.email %></td>
        <td><%= helper.facebook %></td>
        <td><%= helper.comment %></td>
        <td><%= link_to '詳細', helper %></td>
        <td><%= link_to '編集', edit_helper_path(helper) %></td>
        <td><%= link_to '削除', helper, method: :delete, data: { confirm: '削除して良いですか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新しいお手伝いさん登録', new_helper_path %>

app/views/helpers/new.html.erb
<h1>New helper</h1>

<%= render 'form' %>

<%= link_to '助っ人一覧に戻る', helpers_path %>

app/views/helpers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ジャンル:</strong>
  <%= @helper.category.name %>
</p>

<p>
  <strong>スキル、特技:</strong>
  <%= @helper.skill %>
</p>

<p>
  <strong>電話番号:</strong>
  <%= @helper.tel %>
</p>

<p>
  <strong>メールアドレス:</strong>
  <%= @helper.email %>
</p>

<p>
  <strong>Facebookアカウント:</strong>
  <%= @helper.facebook %>
</p>

<p>
  <strong>備考:</strong>
  <%= @helper.comment %>
</p>


  <strong>対応可能スケジュール</strong>
  <table>
  <thead>
    <tr>
      <th>対応可能日</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
  <% @helper.schedules.each do |schedule| %>
  <tr>
    <td><%= schedule.free_date %></td>
    <td><%= link_to '変更', edit_helper_schedule_path(@helper, schedule) %></td>
    <td><%= link_to '削除', helper_schedule_path(@helper, schedule), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
  </tbody>
  </table>

<%= link_to '新規時間追加', new_helper_schedule_path(@helper) %>

<br>

<%= link_to '編集', edit_helper_path(@helper) %> |
<%= link_to '助っ人一覧に戻る', helpers_path %>