config/routes.rb
Rails.application.routes.draw do

  resources :needs do
    resources :pictures
  end

  resources :helpers do
    resources :schedules
  end

  resources :categories do
    resources :helpers
    resources :needs
  end

  get "/view_picture/:id" => "pictures#view_picture", :as => :view_picture

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :need
  validate :file_invalid?

  #写真アップロード用
  def upfile=(upfile)
    self.imagetype = upfile.content_type
    self.image = upfile.read
  end

  private
  def file_invalid?
    ps = ['image/jpeg', 'image/gif', 'image/png']
    errors.add(:image, 'は画像ファイルではありません') if !ps.include?(self.imagetype)
    errors.add(:image, 'のサイズが5MBを超えています') if self.image.length > 5.megabyte
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy, :view_picture]
  before_action :load_need, only: [:show, :edit, :update, :destroy, :new, :create]
  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  def view_picture
    send_data @picture.image, type: @picture.imagetype, disposition: :inline
  end
  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = @need.pictures.create(picture_params)
    # @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to need_path(@need), notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to need_path(@need), notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to need_path(@need), notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def load_need
      @need = Need.find(params[:need_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:upfile, :need_id)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_for [@need, @picture], :html => {:multipart => true} do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :upfile %><br>
    <%= f.file_field :upfile %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<h1>Listing pictures</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Imagetype</th>
      <th>Need</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.image %></td>
        <td><%= picture.imagetype %></td>
        <td><%= picture.need %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_need_picture_path %>

app/views/pictures/new.html.erb
<h1>写真追加</h1>

<%= render 'form' %>

<%= link_to 'お願い詳細に戻る', need_path(@need) %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag view_picture_path(@picture)%></td>
</p>


<%= link_to 'Edit', edit_need_picture_path(@need, @picture) %> |
<%= link_to 'Back', need_pictures_path %>